version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: ls -la && cd .. && ls -la
      - run : |
          aws cloudformation create-stack --stack-name circleci-stack --template-body file://template.yml
workflows:
  workflow:
    jobs:
      - create_infrastructure
