version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["89:9d:db:4b:36:ff:29:00:5d:87:7c:2a:bd:33:93:0c"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook main-remote.yml -i inventory
workflows:
  workflow:
    jobs:
      - create_infrastructure
