version: 2.1
jobs:
  print_repo_owner_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run : echo "Hello my name is $OWNER_NAME"
workflows:
  welcome:
    jobs:
      - print_repo_owner_name
