version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run : |
          aws cloudformation deploy --stack-name circleci-stack --template-file template.yml
workflows:
  workflow:
    jobs:
      - create_infrastructure
